### ISSUE TITLE
Not generating question marks

### ISSUE THREAD

**Issue by genelkim** [genelkim/ulf2english#3]
And probably punctuation in general: 
e.g. bwqa-10
Expected "Does any row contain a red block?" but saw "does any row contain a red block"
 | SENTENCE => "Does any row contain a red block?"
 | (ULF2ENGLISH ULF) => "does any row contain a red block"
 | ULF => (((PRES DO.AUX-S) (ANY.D ROW.N) (CONTAIN.V (A.D (RED.A BLOCK.N)))) ?)

**Comment by gplatono** [comment]
Took care of "?", "!" and "."
