### ISSUE TITLE
incorrect "do" inflection

### ISSUE THREAD

**Issue by bkane2** [genelkim/ulf2english#37]
`((THE.D (|Starbucks| BLOCK.N)) ((PRES DO.AUX-S) NOT.ADV-A (TOUCH.V (THE.D (|Twitter| BLOCK.N)))))` gives `(THE STARBUCKS BLOCK DO NOT TOUCH THE TWITTER BLOCK .)` as output, whereas it should be "DOES"

**Comment by genelkim** [comment]
This turns out not to work because of `NOT.ADV-A`. It should be `NOT` or `NOT.ADV-S`.
